// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include <stdio.h>
#include <unistd.h>
#include "ui.h"

void button_delayed_action(lv_timer_t * timer);

void test(lv_event_t * e)
{
	// Your code here
//    sleep(5);
//    printf("ok\n");
//    lv_obj_t * btn = lv_event_get_target(e);
}

